ARG PYTHON_VERSION=3.9.6

FROM python:$PYTHON_VERSION

# optional arguments at buildtime
# use --build-arg to overwrite the default values
# e.g. docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg USERNAME=$(whoami) ...
ARG UID=1000
ARG GID=1000
ARG USERNAME=python

RUN pip install pipenv && export LC_ALL=C.UTF-8 && export LANG=C.UTF-8

# install some default packages
RUN pip install pandas psycopg2-binary parameterized click pybuilder mockito pyyaml overrides \
    python-dateutil pytz six typing-utils

# create specified user and group
# do a few conditional checks:
# if group with the group name of USERNAME exists, delete it
# if group with the GUD exists, delete it
# if user with the user name of USERNAME exists, delete it (and its home directory)
# if user with the UID exists, delete it (and its home directory)
RUN if getent group $GID; then groupdel -f $(getent group $GID | cut -d : -f 1); fi && \
  if getent group $USERNAME; then groupdel -f $USERNAME; fi && \
  if getent passwd $UID; then userdel -r $(getent passwd 1000 | cut -d : -f 1); fi && \
  if getent passwd $USERNAME; then userdel $USERNAME; fi && \
  groupadd -g "${GID}" $USERNAME && \
  useradd --create-home --no-log-init -u "${UID}" -g "${GID}" $USERNAME

# https://github.com/boxboat/fixuid
# I disabled this section as one can change uid and git by the -u UID:GID flag at runtime.
# Look it up if needed
# RUN USER=python && \
#    GROUP=python && \
#    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.5.1/fixuid-0.5.1-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
#    chown root:root /usr/local/bin/fixuid && \
#    chmod 4755 /usr/local/bin/fixuid && \
#    mkdir -p /etc/fixuid && \
#    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

# USER python:python

# ENTRYPOINT ["fixuid"]

USER $USERNAME

WORKDIR /home/$USERNAME

CMD ["python"]